// Code generated by qtc from "jeniskeluhan.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line jeniskeluhan.qtpl:1
package view

//line jeniskeluhan.qtpl:1
import (
	"b2t_helpdesk/injector"
	"github.com/valyala/fasthttp"
)

//line jeniskeluhan.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line jeniskeluhan.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line jeniskeluhan.qtpl:7
type JenisKeluhan struct {
	CTX       *fasthttp.RequestCtx
	Dinjector *injector.Injector
}

//line jeniskeluhan.qtpl:14
func (p *JenisKeluhan) StreamTitle(qw422016 *qt422016.Writer) {
//line jeniskeluhan.qtpl:14
	qw422016.N().S(`
	Daftar Jenis Keluhan
`)
//line jeniskeluhan.qtpl:16
}

//line jeniskeluhan.qtpl:16
func (p *JenisKeluhan) WriteTitle(qq422016 qtio422016.Writer) {
//line jeniskeluhan.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line jeniskeluhan.qtpl:16
	p.StreamTitle(qw422016)
//line jeniskeluhan.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line jeniskeluhan.qtpl:16
}

//line jeniskeluhan.qtpl:16
func (p *JenisKeluhan) Title() string {
//line jeniskeluhan.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
//line jeniskeluhan.qtpl:16
	p.WriteTitle(qb422016)
//line jeniskeluhan.qtpl:16
	qs422016 := string(qb422016.B)
//line jeniskeluhan.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
//line jeniskeluhan.qtpl:16
	return qs422016
//line jeniskeluhan.qtpl:16
}

//line jeniskeluhan.qtpl:19
func (p *JenisKeluhan) StreamBody(qw422016 *qt422016.Writer) {
//line jeniskeluhan.qtpl:19
	qw422016.N().S(`
	<div class="card shadow mb-4">
		<div class="card-body">
			<button class="btn btn-success" type="button" onclick="readytambah()" data-toggle="modal" data-target="#addModal">Tambah Jenis</button>
			<div class="table-responsive">
				<table class="table table-bordered" width="100%" cellspacing="0">
					<thead>
						<tr>
							<th>#</th>
							<th>ID</th>
							<th>Jenis keluhan</th>
							<th>Hint</th>
							<th>Lanjut Ke Bantuan Langsung</th>
						</tr>
					</thead>
					<tbody>
					`)
//line jeniskeluhan.qtpl:36
	results, _ := p.Dinjector.DB.Query("SELECT id, jenis, hint, autoinput FROM jenisticket ORDER BY id ASC")
	type keluhan struct {
		Id        int    `json:"id"`
		Jenis     string `json:"jenis"`
		Hint      string `json:"hint"`
		Autoinput int    `json:"autoinput"`
	}
	var daftarkeluhan []keluhan
	for results.Next() {
		var buffkeluhan keluhan
		err := results.Scan(&buffkeluhan.Id, &buffkeluhan.Jenis, &buffkeluhan.Hint, &buffkeluhan.Autoinput)
		if err == nil {
			daftarkeluhan = append(daftarkeluhan, buffkeluhan)
		}
	}

//line jeniskeluhan.qtpl:51
	qw422016.N().S(`
					
					`)
//line jeniskeluhan.qtpl:53
	for _, value := range daftarkeluhan {
//line jeniskeluhan.qtpl:53
		qw422016.N().S(`
						<tr>
							<td>
								<button class="btn btn-warning" data-toggle="modal" data-target="#addModal" onclick="readyEdit('`)
//line jeniskeluhan.qtpl:56
		qw422016.N().D(value.Id)
//line jeniskeluhan.qtpl:56
		qw422016.N().S(`')" type="button"><i class="fa fa-edit"></i></button>
								<a href="/jeniskeluhan/delete/`)
//line jeniskeluhan.qtpl:57
		qw422016.N().D(value.Id)
//line jeniskeluhan.qtpl:57
		qw422016.N().S(`"><button class="btn btn-danger" type="button"><i class="fa fa-trash"></i></button></a>
							</td>
							<td>`)
//line jeniskeluhan.qtpl:59
		qw422016.N().D(value.Id)
//line jeniskeluhan.qtpl:59
		qw422016.N().S(`</td>
							<td>`)
//line jeniskeluhan.qtpl:60
		qw422016.E().S(value.Jenis)
//line jeniskeluhan.qtpl:60
		qw422016.N().S(`</td>
							<td>`)
//line jeniskeluhan.qtpl:61
		qw422016.E().S(value.Hint)
//line jeniskeluhan.qtpl:61
		qw422016.N().S(`</td>
							<td>`)
//line jeniskeluhan.qtpl:62
		qw422016.N().D(value.Autoinput)
//line jeniskeluhan.qtpl:62
		qw422016.N().S(`</td>
						</tr>
					`)
//line jeniskeluhan.qtpl:64
	}
//line jeniskeluhan.qtpl:64
	qw422016.N().S(`
					</tbody>
				</table>
			</div>
		</div>
	</div>

`)
//line jeniskeluhan.qtpl:71
}

//line jeniskeluhan.qtpl:71
func (p *JenisKeluhan) WriteBody(qq422016 qtio422016.Writer) {
//line jeniskeluhan.qtpl:71
	qw422016 := qt422016.AcquireWriter(qq422016)
//line jeniskeluhan.qtpl:71
	p.StreamBody(qw422016)
//line jeniskeluhan.qtpl:71
	qt422016.ReleaseWriter(qw422016)
//line jeniskeluhan.qtpl:71
}

//line jeniskeluhan.qtpl:71
func (p *JenisKeluhan) Body() string {
//line jeniskeluhan.qtpl:71
	qb422016 := qt422016.AcquireByteBuffer()
//line jeniskeluhan.qtpl:71
	p.WriteBody(qb422016)
//line jeniskeluhan.qtpl:71
	qs422016 := string(qb422016.B)
//line jeniskeluhan.qtpl:71
	qt422016.ReleaseByteBuffer(qb422016)
//line jeniskeluhan.qtpl:71
	return qs422016
//line jeniskeluhan.qtpl:71
}

//line jeniskeluhan.qtpl:73
func (p *JenisKeluhan) StreamModal(qw422016 *qt422016.Writer) {
//line jeniskeluhan.qtpl:73
	qw422016.N().S(`
	<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-xl" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Tambah / Edit Jenis Keluhan</span></h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
				<form action="/jeniskeluhan/update" method="post">
					<div class="modal-body">
						<div class="row">
							<div class="col-12">
								<div class="form group">
									<input name="id" id="id" type="hidden">
									<label>Jenis</label>
									<input name="jenis" id="jenis" class="form-control" type="text">
									<label>Hint</label>
									<textarea name="hint" id="hint" class="form-control" rows="3"></textarea>
									<label>Lanjut Ke Bantuan Langsung (0 Tidak, 1 Iya)</label>
									<input name="autoinput" id="autoinput" class="form-control" type="number" max="1" min="0">
								</div>
							</div>
						</div>
					</div>
					<div class="modal-footer">
						<button class="btn btn-success" type="submit">Simpan</button>
					</div>
                </form>
            </div>
        </div>
    </div>
`)
//line jeniskeluhan.qtpl:106
}

//line jeniskeluhan.qtpl:106
func (p *JenisKeluhan) WriteModal(qq422016 qtio422016.Writer) {
//line jeniskeluhan.qtpl:106
	qw422016 := qt422016.AcquireWriter(qq422016)
//line jeniskeluhan.qtpl:106
	p.StreamModal(qw422016)
//line jeniskeluhan.qtpl:106
	qt422016.ReleaseWriter(qw422016)
//line jeniskeluhan.qtpl:106
}

//line jeniskeluhan.qtpl:106
func (p *JenisKeluhan) Modal() string {
//line jeniskeluhan.qtpl:106
	qb422016 := qt422016.AcquireByteBuffer()
//line jeniskeluhan.qtpl:106
	p.WriteModal(qb422016)
//line jeniskeluhan.qtpl:106
	qs422016 := string(qb422016.B)
//line jeniskeluhan.qtpl:106
	qt422016.ReleaseByteBuffer(qb422016)
//line jeniskeluhan.qtpl:106
	return qs422016
//line jeniskeluhan.qtpl:106
}

//line jeniskeluhan.qtpl:108
func (p *JenisKeluhan) StreamScript(qw422016 *qt422016.Writer) {
//line jeniskeluhan.qtpl:108
	qw422016.N().S(`
<script>
	function readytambah(){
		$('#id').val("0");
		$('#jenis').val("");
		$('#hint').val("");
		$('#autoinput').val("0");
	}

	function readyEdit(id){
		$.get("/api/infojeniskeluhan/"+id)
		.done(function(data){
			$('#id').val(data.id);
			$('#jenis').val(data.jenis);
			$('#hint').val(data.hint);
			$('#autoinput').val(data.autoinput);
		})
	}
</script>
`)
//line jeniskeluhan.qtpl:127
}

//line jeniskeluhan.qtpl:127
func (p *JenisKeluhan) WriteScript(qq422016 qtio422016.Writer) {
//line jeniskeluhan.qtpl:127
	qw422016 := qt422016.AcquireWriter(qq422016)
//line jeniskeluhan.qtpl:127
	p.StreamScript(qw422016)
//line jeniskeluhan.qtpl:127
	qt422016.ReleaseWriter(qw422016)
//line jeniskeluhan.qtpl:127
}

//line jeniskeluhan.qtpl:127
func (p *JenisKeluhan) Script() string {
//line jeniskeluhan.qtpl:127
	qb422016 := qt422016.AcquireByteBuffer()
//line jeniskeluhan.qtpl:127
	p.WriteScript(qb422016)
//line jeniskeluhan.qtpl:127
	qs422016 := string(qb422016.B)
//line jeniskeluhan.qtpl:127
	qt422016.ReleaseByteBuffer(qb422016)
//line jeniskeluhan.qtpl:127
	return qs422016
//line jeniskeluhan.qtpl:127
}
