// Code generated by qtc from "keluhan.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line keluhan.qtpl:1
package view

//line keluhan.qtpl:1
import (
	"b2t_helpdesk/injector"
	"github.com/tidwall/gjson"
	"github.com/valyala/fasthttp"
)

//line keluhan.qtpl:7
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line keluhan.qtpl:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line keluhan.qtpl:8
type KeluhanPage struct {
	CTX       *fasthttp.RequestCtx
	Dinjector *injector.Injector
}

//line keluhan.qtpl:15
func (p *KeluhanPage) StreamTitle(qw422016 *qt422016.Writer) {
//line keluhan.qtpl:15
	qw422016.N().S(`
	Daftar Keluhan
`)
//line keluhan.qtpl:17
}

//line keluhan.qtpl:17
func (p *KeluhanPage) WriteTitle(qq422016 qtio422016.Writer) {
//line keluhan.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
//line keluhan.qtpl:17
	p.StreamTitle(qw422016)
//line keluhan.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line keluhan.qtpl:17
}

//line keluhan.qtpl:17
func (p *KeluhanPage) Title() string {
//line keluhan.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
//line keluhan.qtpl:17
	p.WriteTitle(qb422016)
//line keluhan.qtpl:17
	qs422016 := string(qb422016.B)
//line keluhan.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
//line keluhan.qtpl:17
	return qs422016
//line keluhan.qtpl:17
}

//line keluhan.qtpl:20
func (p *KeluhanPage) StreamBody(qw422016 *qt422016.Writer) {
//line keluhan.qtpl:20
	qw422016.N().S(`

	<div class="card shadow mb-4">
		<div class="card-header py-3">
			<h6 class="m-0 font-weight-bold text-primary">Filter</h6>
		</div>
		<div class="card-body">
			<div class="row">
				<div class="col-4">
					<div class="form-group">
						<label>Jenis</label>
						<select id="jenisfilter" class="form-control autopulldata">
							<option value="-1">Semua</option>
							`)
//line keluhan.qtpl:34
	var optionval []string
	results, _ := p.Dinjector.DB.Query("SELECT jenis FROM jenisticket ORDER BY id ASC")
	for results.Next() {
		var jenis string
		results.Scan(&jenis)
		optionval = append(optionval, jenis)
	}
	p.Dinjector.Config.Get("keyboardlist").Get("jenisticket").ForEach(func(key gjson.Result, value gjson.Result) bool {
		optionval = append(optionval, value.Get("jenis").String())
		return true
	})

//line keluhan.qtpl:45
	qw422016.N().S(`
							`)
//line keluhan.qtpl:46
	for _, value := range optionval {
//line keluhan.qtpl:46
		qw422016.N().S(`
								<option value="`)
//line keluhan.qtpl:47
		qw422016.E().S(value)
//line keluhan.qtpl:47
		qw422016.N().S(`">`)
//line keluhan.qtpl:47
		qw422016.E().S(value)
//line keluhan.qtpl:47
		qw422016.N().S(`</option>
							`)
//line keluhan.qtpl:48
	}
//line keluhan.qtpl:48
	qw422016.N().S(`
						</select>
					</div>
				</div>
				<div class="col-4">
					<div class="form-group">
						<label>Kelompok</label>
						<select id="kelompokfilter" class="form-control autopulldata">
							<option value="-1">Semua</option>
							`)
//line keluhan.qtpl:58
	var optionval2 []string
	p.Dinjector.Config.Get("keyboardlist").Get("kelompok").ForEach(func(key gjson.Result, value gjson.Result) bool {
		optionval2 = append(optionval2, value.String())
		return true
	})

//line keluhan.qtpl:63
	qw422016.N().S(`
							`)
//line keluhan.qtpl:64
	for _, value := range optionval2 {
//line keluhan.qtpl:64
		qw422016.N().S(`
								<option value="`)
//line keluhan.qtpl:65
		qw422016.E().S(value)
//line keluhan.qtpl:65
		qw422016.N().S(`">`)
//line keluhan.qtpl:65
		qw422016.E().S(value)
//line keluhan.qtpl:65
		qw422016.N().S(`</option>
							`)
//line keluhan.qtpl:66
	}
//line keluhan.qtpl:66
	qw422016.N().S(`
						</select>
					</div>
				</div>
				<div class="col-2">
					<div class="form-group">
						<label>Status</label>
						<select id="statusfilter" class="form-control autopulldata">
							<option value="-1">Semua</option>
							<option value="0">Terbuka</option>
							<option value="1">Tertutup</option>
						</select>
					</div>
				</div>
				<div class="col-2">
					<div class="form-group">
						<label>Openchat</label>
						<select id="openfilter" class="form-control autopulldata">
							<option value="-1">Semua</option>
							<option value="0">Close</option>
							<option value="1">Open</option>
						</select>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="card shadow mb-4">
		<div class="card-header py-3">
			<h6 class="m-0 font-weight-bold text-primary">Data Keluhan
				<a href="#" class="ms-5 btn btn-success btn-sm" id="autosync">
					<i class="fas fa-sync"></i> Auto Refresh
				</a>
				<a href="#" class="ms-3 btn btn-success btn-sm" onclick="intDataTable()">
					<i class="fas fa-sync"></i> Refresh Now!
				</a>
			</h6>
		</div>
		<div class="card-body">
			<div class="table-responsive">
				<table class="table table-bordered" id="dataKeluhan" width="100%" cellspacing="0">
					<thead>
						<tr>
							<th>#</th>
							<th>No</th>
							<th>Nama</th>
							<th>Kelompok</th>
							<th>Jenis</th>
							<th>Status</th>
							<th>Openchat</th>
							<th>Tim</th>
						</tr>
					</thead>
					<tbody>

					</tbody>
				</table>
			</div>
		</div>
	</div>

`)
//line keluhan.qtpl:128
}

//line keluhan.qtpl:128
func (p *KeluhanPage) WriteBody(qq422016 qtio422016.Writer) {
//line keluhan.qtpl:128
	qw422016 := qt422016.AcquireWriter(qq422016)
//line keluhan.qtpl:128
	p.StreamBody(qw422016)
//line keluhan.qtpl:128
	qt422016.ReleaseWriter(qw422016)
//line keluhan.qtpl:128
}

//line keluhan.qtpl:128
func (p *KeluhanPage) Body() string {
//line keluhan.qtpl:128
	qb422016 := qt422016.AcquireByteBuffer()
//line keluhan.qtpl:128
	p.WriteBody(qb422016)
//line keluhan.qtpl:128
	qs422016 := string(qb422016.B)
//line keluhan.qtpl:128
	qt422016.ReleaseByteBuffer(qb422016)
//line keluhan.qtpl:128
	return qs422016
//line keluhan.qtpl:128
}

//line keluhan.qtpl:130
func (p *KeluhanPage) StreamModal(qw422016 *qt422016.Writer) {
//line keluhan.qtpl:130
	qw422016.N().S(`
	<div class="modal fade" id="ticketModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-xl" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Keluhan - <span id="idkeluhan"></span></h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
					<div class="row">
						<div class="col-10">
							<table class="table table-bordered" width="100%" cellspacing="0">
								<tr>
									<td style="width: 1%; white-space: nowrap;">Nama:</td>
									<td id="tbNama"></td>
									<td style="width: 1%; white-space: nowrap;">Kelompok:</td>
									<td id="tbKelompok"></td>
								</tr>
								<tr>
									<td style="width: 1%; white-space: nowrap;">No Reg.:</td>
									<td id="tbNoReg"></td>
									<td style="width: 1%; white-space: nowrap;">Jenis:</td>
									<td id="tbJenis"></td>
								</tr>
							</table>
						</div>
						<div class="col-2">
							<button id="tutupKeluhan" class="btn btn-block" type="button">Tutup Keluhan</button>
							<button id="mulaiChat" class="btn btn-success btn-block mt-3" type="button">Open Chat</button>
						</div>
					</div>
					<div class="row">
						<div class="col-12">
							<p class="text-muted">Jika sesi chat berstatus close (tombol masih berwarna hijau), maka anda tidak dapat membaca balasan pesan (sesi hanya 1 arah).<br />Silahkan buka sesi openchat jika ingin membuka sesi 2 arah</p>
							<div class="px-4 py-5 chat-box bg-white border border-primary" id="chatbox"></div>
							<!-- Typing area -->
							<div id="typingArea" class="bg-light">
								<div class="input-group">
								<textarea id="textpesan" type="text" placeholder="Ketik pesan anda" aria-describedby="btnkirimchat" class="form-control rounded-0 border-0 py-4 bg-light" row="4"></textarea>
								<div class="input-group-append">
									<button id="btnkirimchat" type="button" class="btn btn-link"> <i class="fa fa-paper-plane"></i></button>
								</div>
								</div>
							</div>
						</div>
					</div>
				</div>
                
            </div>
        </div>
    </div>
`)
//line keluhan.qtpl:183
}

//line keluhan.qtpl:183
func (p *KeluhanPage) WriteModal(qq422016 qtio422016.Writer) {
//line keluhan.qtpl:183
	qw422016 := qt422016.AcquireWriter(qq422016)
//line keluhan.qtpl:183
	p.StreamModal(qw422016)
//line keluhan.qtpl:183
	qt422016.ReleaseWriter(qw422016)
//line keluhan.qtpl:183
}

//line keluhan.qtpl:183
func (p *KeluhanPage) Modal() string {
//line keluhan.qtpl:183
	qb422016 := qt422016.AcquireByteBuffer()
//line keluhan.qtpl:183
	p.WriteModal(qb422016)
//line keluhan.qtpl:183
	qs422016 := string(qb422016.B)
//line keluhan.qtpl:183
	qt422016.ReleaseByteBuffer(qb422016)
//line keluhan.qtpl:183
	return qs422016
//line keluhan.qtpl:183
}

//line keluhan.qtpl:185
func (p *KeluhanPage) StreamScript(qw422016 *qt422016.Writer) {
//line keluhan.qtpl:185
	qw422016.N().S(`
<script>
	var dataKeluhan_table;
	var intervaldatatable;
	$(document).ready(function(){
		dataKeluhan_table = $('#dataKeluhan').DataTable({
			"processing": true,
			"serverSide": true,
			"lengthMenu": [ 10, 25, 50, 75, 100 ],
			"ajax": {
						"url" : "/api/datakeluhantable",
						"type": "POST",
						"data": function ( d ) {
								return $.extend( {}, d, {
									"jenisfilter": $("#jenisfilter").val(),
									"kelompokfilter": $("#kelompokfilter").val(),
									"statusfilter": $("#statusfilter").val(),
									"openfilter": $("#openfilter").val(),
								} );
						},
					},
			"columns" : [
				{
					"searchable":      false,
					"data":           "id",
					"className":      "dt-body-center nowrap",
					"render": function( data, type, row, meta ) {
						return '<button class="btn btn-success" type="button" onclick="openTicket('+data+')">'+data+'</button>';
					}
				},
				{ "data": "no" },
				{ "data": "nama" },
				{ "data": "kelompok" },
				{ "data": "jenis" },
				{ "data": "status" },
				{ "data": "openchat" },
				{ "data": "tim" },
			],
			"order": [[0, 'desc']],
			initComplete: function(){
				var api = this.api();
				$('#dataKeluhan_filter input')
					.off('.DT')
					.on('keyup.DT', function (e) {
						if (e.keyCode == 13) {
							api.search(this.value).draw();
						}
					});
			}
		});

		$(".autopulldata").change(function(){
			dataKeluhan_table.ajax.reload();
		});

		$("#autosync").click(function(){
			if ($("#autosync").hasClass("btn-success")) {
				$("#autosync").removeClass("btn-success").addClass("btn-danger");
				$("#autosync").find("i.fas").removeClass("fa-sync").addClass("fa-times");
				intervaldatatable = setInterval(intDataTable,3000);

			} else {
				$("#autosync").removeClass("btn-danger").addClass("btn-success");
				$("#autosync").find("i.fas").removeClass("fa-times").addClass("fa-sync");
				clearInterval(intervaldatatable);
			}
		});
	});

	function intDataTable() {
		dataKeluhan_table.ajax.reload(null, false);
	}

	var intervalchat;
	var idpesanakhir;
	var idopenticket;
	var petugas;
	function openTicket(id) {
		$('#idkeluhan').html(id);

		idopenticket = id;

		//fetch data
		$.get("/api/infoticket/"+id)
		.done(function(data){
			$('#tbNama').html(data.nama);
			$('#tbNoReg').html(data.no);
			$('#tbKelompok').html(data.kelompok);
			$('#tbJenis').html(data.jenis);

			if (data.status == 0) {
				$('#tutupKeluhan').removeClass('btn-danger').addClass('btn-warning').html("Tutup Keluhan");
				$('#mulaiChat').show();
				$('#typingArea').show();
			} else {
				$('#tutupKeluhan').removeClass('btn-warning').addClass('btn-danger').html("Buka Lagi Keluhan");
				$('#mulaiChat').hide();
				$('#typingArea').hide();
			}

			if (data.openchat == 0) {
				$('#mulaiChat').removeClass('btn-danger').addClass('btn-success').html("Buka Sesi Chat");
			} else {
				$('#mulaiChat').removeClass('btn-success').addClass('btn-danger').html("Tutup Sesi Chat");
			}

			idpesanakhir = 0;
			reloadPesanChat();

			intervalchat = setInterval(reloadPesanChat,3000);
		})

		//show modal
		$("#ticketModal").modal('show');
	}

	function reloadPesanChat() {
		if (idpesanakhir == 0) {
			$('#chatbox').html('');
		}

		$.get("/api/chatticket/"+idopenticket+"/"+idpesanakhir)
		.done(function(data){
			$.each(data.chat, function(i,v){
				if (v.penulis.length < 1) {
					//customer
					out = '<div class="media w-50 mb-3"><img src="/static/img/undraw_profile.svg" alt="user" width="50" class="rounded-circle">';
					out += '<div class="media-body ml-3">';
					out += '<div class="bg-light rounded py-2 px-3 mb-2">';
					out += '<p class="text-small mb-0 text-muted">'+v.pesan+'</p>';
					if (v.file.length > 1) {
						out += '<img src="/photos/'+v.file+'" class="img-responsive" style="width: 100%;">';
					}
					out += '</div>';
					out += '<p class="small text-muted">'+v.timestamp+'</p>';
					out += '</div></div>';
					$('#chatbox').append(out);
				} else {
					//pegawai
					out = '<div class="media w-50 ml-auto mb-3">';
					out += '<div class="media-body">';
					out += '<div class="bg-primary rounded py-2 px-3 mb-2">';
					out += '<p class="text-small mb-0 text-white">'+v.pesan+'</p>';
					out += '</div>';
					out += '<p class="small text-muted">'+v.timestamp+' | '+v.penulis+'</p>';
					out += '</div></div>';
					$('#chatbox').append(out);
				}
				idpesanakhir = v.id;
			})
		})
	}

	$(document).ready(function(){
		$("#mulaiChat").click(function(){
			if ($('#mulaiChat').hasClass('btn-success')) {
				$.get("/api/openchat/"+idopenticket)
				.done(function(data){
					$('#mulaiChat').removeClass('btn-success').addClass('btn-danger').html("Tutup Sesi Chat");
				})
			} else {
				$.get("/api/closechat/"+idopenticket)
				.done(function(data){
					$('#mulaiChat').removeClass('btn-danger').addClass('btn-success').html("Buka Sesi Chat");
				})
			}
		});
		$("#btnkirimchat").click(function(){
			if ($("#textpesan").val().length < 5) {
				alert("Pesan minimal 5 karakter");
				return false;
			}

			$("#btnkirimchat").hide();
			datapost = {
				"pesan" : $('#textpesan').val(),
				"pegawai" : petugas,
			};
			$.post("/api/sendchat/"+idopenticket, datapost)
			.done(function(data){
				reloadPesanChat();
				$('#textpesan').val('').focus();
			})

			setTimeout(function() {
				$("#btnkirimchat").show();
			}, 2000);
		});
		$('#ticketModal').on('hidden.bs.modal', function (e) {
			clearInterval(intervalchat);
		})
		$('#tutupKeluhan').click(function(){
			if ($('#tutupKeluhan').hasClass("btn-warning")) {
				$.get("/api/closekeluhan/"+idopenticket)
				.done(function(data){
					$('#tutupKeluhan').removeClass('btn-warning').addClass('btn-danger').html("Buka Keluhan");
					$('#mulaiChat').hide();
					$('#typingArea').hide();
				})
			} else {
				$.get("/api/openkeluhan/"+idopenticket)
				.done(function(data){
					$('#tutupKeluhan').removeClass('btn-danger').addClass('btn-warning').html("Tutup Keluhan");
					$('#mulaiChat').show();
					$('#typingArea').show();
				})
			}
		});

		Swal.fire({
			title: 'Mohon inputkan nama anda',
			input: 'text',
			inputLabel: 'Nama Anda',
			inputPlaceholder: 'Masukan nama anda',
			allowOutsideClick: false,
			showCancelButton: false,
			showCloseButton: false,
			allowEscapeKey: false,
		}).then((result) => {
			if (result.value) {
				petugas = result.value;
			} else {
				location.reload();
			}
		});
	});
</script>
`)
//line keluhan.qtpl:412
}

//line keluhan.qtpl:412
func (p *KeluhanPage) WriteScript(qq422016 qtio422016.Writer) {
//line keluhan.qtpl:412
	qw422016 := qt422016.AcquireWriter(qq422016)
//line keluhan.qtpl:412
	p.StreamScript(qw422016)
//line keluhan.qtpl:412
	qt422016.ReleaseWriter(qw422016)
//line keluhan.qtpl:412
}

//line keluhan.qtpl:412
func (p *KeluhanPage) Script() string {
//line keluhan.qtpl:412
	qb422016 := qt422016.AcquireByteBuffer()
//line keluhan.qtpl:412
	p.WriteScript(qb422016)
//line keluhan.qtpl:412
	qs422016 := string(qb422016.B)
//line keluhan.qtpl:412
	qt422016.ReleaseByteBuffer(qb422016)
//line keluhan.qtpl:412
	return qs422016
//line keluhan.qtpl:412
}
