// Code generated by qtc from "rmq.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line rmq.qtpl:1
package view

//line rmq.qtpl:1
import (
	"b2t_helpdesk/injector"
	"github.com/valyala/fasthttp"
)

//line rmq.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line rmq.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line rmq.qtpl:7
type RmqPage struct {
	CTX       *fasthttp.RequestCtx
	Dinjector *injector.Injector
}

//line rmq.qtpl:14
func (p *RmqPage) StreamTitle(qw422016 *qt422016.Writer) {
//line rmq.qtpl:14
	qw422016.N().S(`
	Message Queue Stats
`)
//line rmq.qtpl:16
}

//line rmq.qtpl:16
func (p *RmqPage) WriteTitle(qq422016 qtio422016.Writer) {
//line rmq.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line rmq.qtpl:16
	p.StreamTitle(qw422016)
//line rmq.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line rmq.qtpl:16
}

//line rmq.qtpl:16
func (p *RmqPage) Title() string {
//line rmq.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
//line rmq.qtpl:16
	p.WriteTitle(qb422016)
//line rmq.qtpl:16
	qs422016 := string(qb422016.B)
//line rmq.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
//line rmq.qtpl:16
	return qs422016
//line rmq.qtpl:16
}

//line rmq.qtpl:19
func (p *RmqPage) StreamBody(qw422016 *qt422016.Writer) {
//line rmq.qtpl:19
	qw422016.N().S(`
	<div class="card shadow mb-4">
		<div class="card-body">
			`)
//line rmq.qtpl:23
	stat, _ := p.Dinjector.QConn.CollectStats([]string{"outbox-b2t"})

//line rmq.qtpl:24
	qw422016.N().S(`
			<pre>`)
//line rmq.qtpl:25
	qw422016.E().S(stat.String())
//line rmq.qtpl:25
	qw422016.N().S(`</pre>
		</div>
	</div>
	<div class="card shadow mb-4">
		<div class="card-body">
			<p class="text-muted">Reload konfigurasi JSON</p>
			<a href="/reload" class="btn btn-warning">Reload Konfigurasi JSON</a>
		</div>
	</div>
	<div class="card shadow mb-4">
		<div class="card-body">
			<p class="text-muted">Hati-hati, tombol ini akan menghapus data peserta, keluhan, dan chats (Kecuali daftar jenis keluhan)</p>
			<a href="/resetdatakeluhan" class="btn btn-danger" onclick="return confirm('Apakah anda yakin mereset data? (tidak bisa dikembalikan)')">RESET DATA</a>
		</div>
	</div>

`)
//line rmq.qtpl:41
}

//line rmq.qtpl:41
func (p *RmqPage) WriteBody(qq422016 qtio422016.Writer) {
//line rmq.qtpl:41
	qw422016 := qt422016.AcquireWriter(qq422016)
//line rmq.qtpl:41
	p.StreamBody(qw422016)
//line rmq.qtpl:41
	qt422016.ReleaseWriter(qw422016)
//line rmq.qtpl:41
}

//line rmq.qtpl:41
func (p *RmqPage) Body() string {
//line rmq.qtpl:41
	qb422016 := qt422016.AcquireByteBuffer()
//line rmq.qtpl:41
	p.WriteBody(qb422016)
//line rmq.qtpl:41
	qs422016 := string(qb422016.B)
//line rmq.qtpl:41
	qt422016.ReleaseByteBuffer(qb422016)
//line rmq.qtpl:41
	return qs422016
//line rmq.qtpl:41
}

//line rmq.qtpl:43
func (p *RmqPage) StreamModal(qw422016 *qt422016.Writer) {
//line rmq.qtpl:43
	qw422016.N().S(`
	
`)
//line rmq.qtpl:45
}

//line rmq.qtpl:45
func (p *RmqPage) WriteModal(qq422016 qtio422016.Writer) {
//line rmq.qtpl:45
	qw422016 := qt422016.AcquireWriter(qq422016)
//line rmq.qtpl:45
	p.StreamModal(qw422016)
//line rmq.qtpl:45
	qt422016.ReleaseWriter(qw422016)
//line rmq.qtpl:45
}

//line rmq.qtpl:45
func (p *RmqPage) Modal() string {
//line rmq.qtpl:45
	qb422016 := qt422016.AcquireByteBuffer()
//line rmq.qtpl:45
	p.WriteModal(qb422016)
//line rmq.qtpl:45
	qs422016 := string(qb422016.B)
//line rmq.qtpl:45
	qt422016.ReleaseByteBuffer(qb422016)
//line rmq.qtpl:45
	return qs422016
//line rmq.qtpl:45
}

//line rmq.qtpl:47
func (p *RmqPage) StreamScript(qw422016 *qt422016.Writer) {
//line rmq.qtpl:47
	qw422016.N().S(`

`)
//line rmq.qtpl:49
}

//line rmq.qtpl:49
func (p *RmqPage) WriteScript(qq422016 qtio422016.Writer) {
//line rmq.qtpl:49
	qw422016 := qt422016.AcquireWriter(qq422016)
//line rmq.qtpl:49
	p.StreamScript(qw422016)
//line rmq.qtpl:49
	qt422016.ReleaseWriter(qw422016)
//line rmq.qtpl:49
}

//line rmq.qtpl:49
func (p *RmqPage) Script() string {
//line rmq.qtpl:49
	qb422016 := qt422016.AcquireByteBuffer()
//line rmq.qtpl:49
	p.WriteScript(qb422016)
//line rmq.qtpl:49
	qs422016 := string(qb422016.B)
//line rmq.qtpl:49
	qt422016.ReleaseByteBuffer(qb422016)
//line rmq.qtpl:49
	return qs422016
//line rmq.qtpl:49
}
